language: python
before_install:
- sudo add-apt-repository --yes ppa:fontforge/fontforge
- sudo apt-get update -qq
- sudo apt-get install python-fontforge ttfautohint
- cp /usr/lib/python2.7/dist-packages/fontforge.* "$HOME/virtualenv/python2.7.8/lib/python2.7/site-packages"
install:
- pip install git+https://github.com/behdad/fontTools.git
- pip install git+https://github.com/googlefonts/fontcrunch.git
- pip install git+https://github.com/googlefonts/fontbakery-cli.git
- pip install jinja2
before_script:
- mkdir -p builds/build
script: PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH fontbakery-build.py .
  2>&1 | tee -a builds/build/buildlog.txt
branches:
  only:
  - master
after_script:
- PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH fontbakery-report.py builds/build
- rm -rf builds/build/sources
- rm -rf builds/build/build.state.yaml
- PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH fontbakery-travis-deploy.py
env:
  global:
    secure: EDePQBEY1o3WTzyrN94tg/PygOJQSlM2oK7SDW+paj+kcmJ/bMnfzV3u2n3wo/Or6M1mDkbIiafeV7GAcfHK7Ha6h3Yk1yHSrWACVx85h5xb2GgXE6PFVUBif9io3/2lUx1JN91J6ZnEP4UK8WY6PWJAZz95l+YCl3Q50H/eSaQ=
